language: ruby
rvm:
- 2.3.1
install:
- bundle install
before_deploy:
  - if [ "$TRAVIS_BRANCH" == "source" ];then
    git checkout source;
    fi;
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: src
  fqdn: spruce.com.ng
  target_branch: master
  keep_history: true
  on:
    branch: source
